set veri off feed off echo off lines 1000 pages 0
ALTER SESSION SET nls_date_format='DD-MM-YYYY hh24:mi:ss'

SELECT '"'||USER_ID||'","'||HEARDBY||'","'||FRIEND_ID||'","'||CAMPAIGN_ID||'","'||INSERT_DATE||'","'||USER_IP||'","'||USER_LOCATION||'","'||MAC_ADDRESS||'","'||ROOM_ID||'","'||CREATEDBY||'","'||DATECREATED||'","'||UPDATEDBY||'","'||DATEUPDATED||'","'||COUNTRY_CODE||'","'||STATE||'","'||CITY||'","'||CLIENT_TYPE||'","'||CLIENT_VERSIONNO||'","'||OPERATING_SYSTEM||'","'||BROWSER||'","'||USEDFOR_TYPE||'","'||REGISTRATION_PRODUCT_ID||'","'||REGISTRATION_TRIAL_PERIOD||'","'||DOWNLOAD_GUID||'","'||CHANNEL_ITEM_ID||'","'||CHANNEL_DATACREATE_COOKIE||'","'||MACHINE_NAME||'","'||REGISTRATION_GUID||'","'||SUB_CLIENT_TYPE||'"' FROM app.CAMPAIGN_DATA;

-- "USER_ID","HEARDBY","FRIEND_ID","CAMPAIGN_ID","INSERT_DATE","USER_IP","USER_LOCATION","MAC_ADDRESS","ROOM_ID","CREATEDBY","DATECREATED","UPDATEDBY","DATEUPDATED","COUNTRY_CODE","STATE","CITY","CLIENT_TYPE","CLIENT_VERSIONNO","OPERATING_SYSTEM","BROWSER","USEDFOR_TYPE","REGISTRATION_PRODUCT_ID","REGISTRATION_TRIAL_PERIOD","DOWNLOAD_GUID","CHANNEL_ITEM_ID","CHANNEL_DATACREATE_COOKIE","MACHINE_NAME","REGISTRATION_GUID","SUB_CLIENT_TYPE"

exit
