set veri off feed off echo off lines 1000 pages 0
ALTER SESSION SET nls_date_format='DD-MM-YYYY hh24:mi:ss'

SELECT '"'||USER_ID||'","'||BIRTH_DATE||'","'||GENDER_CODE||'","'||REGISTRATION_SOURCE||'","'||REG_CAMPAIGN_ID||'","'||CHANNEL_VENDOR_ID||'","'||CLIENT_TYPE_GK_ID||'","'||COUNTRY_CODE||'","'||STATE||'","'||CITY||'","'||CLIENT_TYPE||'","'||LANGUAGE||'","'||CHANNEL_VENDOR_NAME||'","'||EMAIL_ADDRESS||'"' FROM OPS$ORACLE.TEMP_FOR_EXECT_TARGET;

-- "USER_ID","BIRTH_DATE","GENDER_CODE","REGISTRATION_SOURCE","REG_CAMPAIGN_ID","CHANNEL_VENDOR_ID","CLIENT_TYPE_GK_ID","COUNTRY_CODE","STATE","CITY","CLIENT_TYPE","LANGUAGE","CHANNEL_VENDOR_NAME","EMAIL_ADDRESS"

exit
