#!/usr/bin/ksh 

if [ $# -eq 0 ]; then
   echo -en "\n\n\t Usage: $0 <table_name> <user_name>\n\n"
   exit 1
fi
UT=`echo $1 | tr [a-z] [A-Z]`
UN=`echo $2 | tr [a-z] [A-Z]`


sqlplus -s / << *EOF*
set echo off lines 150 verify off feedback off

col column_name         for a30
col uniqtype            for a6  head "Uniq"
col Column_position     for 999 head "Col|Pos"
col typeof              for a4  head "Type"
col namstat             for a35 head "Column Name"
col pos                 for 999 head "Col|Pos"
col tsstat              for a35 head "TableSpace"

BREAK ON owner ON table_name ON index_name SKIP 1

DEFINE uname=$UN
DEFINE tname=$UT

tti 'INDEXES For Owner: &uname On TABLE: &tname|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'

SELECT  /*+ CHOOSE */
        uidx.index_name index_name,
        SUBSTR(uidx.uniqueness,1,3) uniqtype,
        uic.column_name namstat,
        uic.column_position pos,
        uidx.TABLESPACE_NAME tsstat
 FROM   dba_ind_columns uic,
        dba_indexes uidx
WHERE   uic.index_owner=uidx.owner
  AND   uic.table_owner=uidx.table_owner
  AND   uidx.table_owner LIKE '&uname'
  AND   (uic.index_name=uidx.index_name)
  AND   (uic.table_name=uidx.Table_name)
  AND   uidx.Table_name LIKE '&tname'
ORDER   BY uniqtype,index_name,pos;


break on constraint_name skip 1
tti 'Constraints For Owner: &uname On TABLE: &tname|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'

col const_cond  for a45

-- prompt Constraint Name                Type   Constrait Condition                           Status
-- prompt ------------------------------ ------ --------------------------------------------- ----------

SELECT  /*+ CHOOSE */
        const.constraint_name                                                           	AS "Constraint Name",
        DECODE(const.constraint_type,'R','FRIGN','C','Check','P','PRIMRY',NULL)  					AS Type,
        const.search_condition                                                            AS "Constrait Condition",
        const.status 		                                                                  AS Status
 FROM   dba_constraints const
WHERE   const.OWNER LIKE '&uname'
  AND   const.Table_name LIKE '&tname'
  AND   const.constraint_type <> 'R'
ORDER   BY  1,4;
-- ORDER   BY owner,table_name,uniqtype,constraint_name,tsstat;

set linesize 158
set verify   off
set pagesize 40

break on constraint_name on r_constraint_name skip 1

column owner format a9
column r_owner format a9
column column_name format a25
column tt noprint
column position heading P format 9
column table_name format a25
column r_table_name format a25
column constraint_name format a25
column r_constraint_name format a22     head "Ref. Const. Name"

tti 'Foreign Keys and Referential Integrity Constraints Columns For Owner: &uname On TABLE: &tname|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-'

select
        a.tt
--        ,a.owner
        ,b.table_name
        ,a.constraint_name
        ,b.column_name
        ,b.position
        ,c.table_name r_table_name
        ,a.r_constraint_name
        ,c.column_name
        ,c.position
--        ,a.r_owner
from
        (select
                owner,
                constraint_name,
                r_constraint_name,
                r_owner,1 tt
        from
                dba_constraints
        where
                owner=upper('&uname')
                and table_name=upper('&tname')
                and constraint_type!='C'
        union
        select
                owner,
                constraint_name,
                r_constraint_name,
                r_owner,2
        from
                dba_constraints
        where
                (r_constraint_name,r_owner) in
                (select
                        constraint_name,
                        owner
                from
                        dba_constraints
                where
                        owner=upper('&uname')
                        and table_name=upper('&tname'))
        ) a,
        dba_cons_columns b,
        dba_cons_columns c
where
        b.constraint_name=a.constraint_name
        and b.owner=a.owner
        and c.constraint_name=a.r_constraint_name
        and c.owner=a.r_owner
        and b.position=c.position
order   by 1,2,3,4,5
/
*EOF*
#fi
