#!/usr/bin/ksh 

if [ $# -ne 2 ] ; then
   echo "\n\tUsage: showutab [ <user_name> | <part_of_uname> ] [ <tab_name> | <part_of_tab_name> ]\n"
else
UN=`echo $1 | tr [a-z] [A-Z]`
UT=`echo $2 | tr [a-z] [A-Z]`

sqlplus -s $USHOW/${PSHOW} << *EOF*
set echo off lines 200 verify off feedback off

Column Column_Name for a30
Column uniqtype head "Uniq|or|TYPE" for a6
Column Column_position head "Col|Pos" for 999
Column owner for a10
col typeof for a4 head "Type|Of"
col namstat for a24 head "Column Name|Constrait Status"

break on owner on table_name on index_name skip 1

define uname=$UN
define tname=$UT

SELECT  /*+ CHOOSE */
        uidx.owner,
        uidx.table_name,
        uidx.index_name,
        'IDX' typeof,
        SUBSTR(uidx.uniqueness,1,3) uniqtype,
        uic.column_name namstat,
        uic.column_position
FROM  dba_ind_columns uic, dba_indexes uidx
WHERE uic.index_owner=uidx.owner
  AND uic.table_owner=uidx.table_owner
  AND uidx.table_owner LIKE '&uname%'
  AND (uic.index_name=uidx.index_name)
  AND (uic.table_name=uidx.Table_name)
  AND uidx.Table_name LIKE '%&tname'
order by 1,2,4,3,7
/

prompt

exit;
*EOF*
fi
