#!/usr/bin/ksh 

#---------------------------------------------------
# USAGE
#---------------------------------------------------
Usage () {
   echo -en "\n\tUsage: showutab  -u <user_name> -t <tab_name> -p <segment_type> -s <tbs>\n\n"
   echo -en "\tSegment Types:\tCACHE\n"
   echo -en "\t\t\tCLUSTER\n"
   echo -en "\t\t\tINDEX\n"
   echo -en "\t\t\tINDEX PARTITION\n"
   echo -en "\t\t\tLOBINDEX\n"
   echo -en "\t\t\tLOBSEGMENT\n"
   echo -en "\t\t\tROLLBACK\n"
   echo -en "\t\t\tTABLE\n"
   echo -en "\t\t\tTABLE PARTITION\n\n"

   exit
}

#---------------------------------------------------
# Show tables/indexes location and size
#---------------------------------------------------
ShowUtab2 () {
sqlplus -s / << *EOF*
set echo off 
-- set feedback off 
set verify off 
set linesize 152 pages 600

col owner               for a10         head Owner
col segment_name        for a29         head "Segment Name"
col partition_name	for a30		head "Partition Name"
col tablespace_name     for a30         head "TS Name"
col segment_type        for a10     	head Type
col extents             for 99999       head Ext
col blocks              for 99,999,999  head Blocks
col MB                  for 9,999,999
col freelists           for 999         head "Free ls"

define tname=$1
define uname=$2
define stype=$3
define ts=$4

break on report
compute sum of MB on report

prompt
prompt *** Table: &tname, User: &uname, Seg Type: &stype, TBS: &ts
prompt $1 Details:

SELECT owner, segment_name, partition_name, tablespace_name,
       DECODE(segment_type,'TABLE PARTITION','TAB PAR','INDEX PARTITION','IDX PAR',segment_type) segment_type,
       extents, blocks, bytes/1024/1024 MB, freelists
 FROM  dba_segments
WHERE (segment_name LIKE UPPER('%&tname%') OR
       segment_name IN (SELECT table_name FROM dba_tables WHERE iot_name LIKE UPPER('%&tname%'))) 
  AND  owner = UPPER('&uname')
  AND  segment_type LIKE UPPER('&stype%')
  AND  tablespace_name LIKE ('&ts')
/
-- UNION  ALL
-- SELECT owner, segment_name, partition_name, tablespace_name,
--        DECODE(segment_type,'TABLE PARTITION','TABLE PAR',segment_type) segment_type,
--        extents, blocks, bytes/1024/1024 MB, freelists
--  FROM  dba_segments
-- WHERE  segment_name IN (SELECT table_name FROM dba_tables WHERE iot_name LIKE UPPER('%&tname%'))
--   AND  owner = UPPER('&uname')
--   AND  segment_type LIKE UPPER('&stype')
--   AND  tablespace_name LIKE ('&ts')
-- ORDER  BY owner, segment_name
-- /

prompt
*EOF*
}

#---------------------------------------------------
# Show tables/indexes location and size
#---------------------------------------------------
ShowUtab () {
sqlplus -s $USHOW/${PSHOW} << *EOF*
set echo off feedback off verify off linesize 152 pages 600

col owner 		for a10
col segment_name	for a35
col tablespace_name	for a25
col MB                  for 9,999,999

break on owner

define uname=$1
define tname=$2

SELECT  /*+ CHOOSE */ 
	owner,
	table_name,
	tablespace_name
--	bytes/1024/1024 MB
FROM  dba_tables seg
WHERE owner LIKE UPPER('&uname%')
AND   table_name LIKE UPPER('%&tname%')
-- $SQL
ORDER BY 1,2
/

prompt

exit;
*EOF*
}
 
#---------------------------------------------------
# MAin
#---------------------------------------------------
STYPE=%
TS=%
USER=
TABLE=
while getopts t:s:p:u: opt
do
    case "$opt" in
       t  )  TABLE="$OPTARG"
             ;;
       s  )  TS="$OPTARG"
#             Action=$opt
             ;;
       p  )  STYPE="$OPTARG"
             ;;
       u  )  USER="$OPTARG"
             ;;
       \? )  # unknown flag
             Usage
             exit 1
             ;;
    esac
done
shift `expr $OPTIND - 1`

ShowUtab2 $TABLE $USER "${STYPE}" "${TS}"
