break on report
compute sum of SYSTEM on report                                                                                                                                                                                                                                                                                                                                                                                 
col SYSTEM for 999,999                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of RBS on report                                                                                                                                                                                                                                                                                                                                                                                    
col RBS for 999,999                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of TEMP on report                                                                                                                                                                                                                                                                                                                                                                                   
col TEMP for 999,999                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of POOL_DATA on report                                                                                                                                                                                                                                                                                                                                                                              
col POOL_DATA for 999,999                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of USER_DATA on report                                                                                                                                                                                                                                                                                                                                                                              
col USER_DATA for 999,999                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of USER_INDEXES on report                                                                                                                                                                                                                                                                                                                                                                           
col USER_INDEXES for 999,999                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of VOLTEST_DATA on report                                                                                                                                                                                                                                                                                                                                                                           
col VOLTEST_DATA for 999,999                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of VOLTEST_IX on report                                                                                                                                                                                                                                                                                                                                                                             
col VOLTEST_IX for 999,999                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of PRECISE on report                                                                                                                                                                                                                                                                                                                                                                                
col PRECISE for 999,999                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                
compute sum of DRSYS on report                                                                                                                                                                                                                                                                                                                                                                                  
col DRSYS for 999,999                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                
