REM this script should be run by user with select any table priv.
REM this script return statistics on enqueue waits on instance level
REM for now it just a hundred from hundreds of enqueues that oracle have
REM any comments welcome 
REM Evgeny Gelfand
col "Enqueue Name" for a60
set lines 100
REM TS explain in v$lock if 
REM ID2=0 then Temporary segment lock enqueue 
REM ID2=1 then New block allocation lock enqueue 
select KSQSTTYP, decode( KSQSTTYP,
'BL','Buffer cache management',
'CF','Control file transaction',
'CI','Cross-instance call invocation',
'CU','Cursor bind enqueue',
'CS','Control file schema global enqueue',
'DF','Data file instance enqueue',
'DL','Direct loader index creation',
'DM','Mount/startup db primary/secondary instance enqueue',
'DR','Distributed recovery process enqueue',
'DX','Distributed transaction entry enqueue',
'FI','SGA open-file information enqueue',
'FS','File set enqueue',
'HW','Space management operations on a specific segment enqueue',
'IN','Instance number enqueue',
'IR','Instance recovery serialization global lock enqueue',
'IS','Instance state enqueue',
'IV','Library cache invalidation instance enqueue',
'JQ','Job queue enqueue',
'KK','redo log kick enqueue',
'MB','Master buffer hash table instance enqueue',
'MM','Mount definition gloabal lock enqueue',
'MR','Media recovery enqueue',
'PF','Password file enqueue',
'PI','Parallel slaves enqueue',
'PR','Process startup enqueue',
'PS','Parallel slave synchronization enqueue',
'RE','USE_ROW_ENQUEUE enforcement enqueue',
'RT','Redo thread global lock enqueue',
'RW','Row wait lock enqueue',
'SC','System commit number instance enqueue',
'SH','System commit number high water mark lock enqueue',
'SM','SMON enqueue',
'SN','Sequence number instance enqueue',
'SQ','Sequence number lock enqueue',
'SR','Synchronized replication',
'SS','Sort segment enqueue',
'ST','Space management transaction lock enqueue',
'SV','Sequence number value enqueue',
'TA','Transaction Recovery enqueue',
'TC','Tablespace Checkpoint wait',
'TD','DDL lock enqueue',
'TE','Extend-segment lock enqueue',
'TM','DML lock enqueue',
'TT','Temporary table lock enqueue',
'TX','Transaction lock enqueue',
'TS','Temporary segment also tablespace lock enqueue',
'UL','User supplied enqueue',
'UN','User name enqueue',
'US','Undo segment DDL/serialization enqueue',
'WL','Being-written redo log instance enqueue',
'WS','Write-atomic-log-switch global lock enqueue',
'XA','Instance attribute lock',
'XI','Instance registration lock',
'LA','Library cache lock instance enqueue (A=namespace)',
'LB','Library cache lock instance enqueue (B=namespace)',
'LC','Library cache lock instance enqueue (C=namespace)',
'LD','Library cache lock instance enqueue (D=namespace)',
'LE','Library cache lock instance enqueue (E=namespace)',
'LF','Library cache lock instance enqueue (F=namespace)',
'LG','Library cache lock instance enqueue (G=namespace)',
'LH','Library cache lock instance enqueue (H=namespace)',
'LI','Library cache lock instance enqueue (I=namespace)',
'LJ','Library cache lock instance enqueue (J=namespace)',
'LK','Library cache lock instance enqueue (K=namespace)',
'LL','Library cache lock instance enqueue (L=namespace)',
'LM','Library cache lock instance enqueue (M=namespace)',
'LN','Library cache lock instance enqueue (N=namespace)',
'LO','Library cache lock instance enqueue (O=namespace)',
'LP','Library cache lock instance enqueue (P=namespace)',
'LS','Log start/log switch lock enqueue',
'NA','Library cache pin instance enqueue (A=namespace)',
'NB','Library cache pin instance enqueue (B=namespace)',
'NC','Library cache pin instance enqueue (C=namespace)',
'ND','Library cache pin instance enqueue (D=namespace)',
'NE','Library cache pin instance enqueue (E=namespace)',
'NF','Library cache pin instance enqueue (F=namespace)',
'NG','Library cache pin instance enqueue (G=namespace)',
'NH','Library cache pin instance enqueue (H=namespace)',
'NI','Library cache pin instance enqueue (I=namespace)',
'NJ','Library cache pin instance enqueue (J=namespace)',
'NL','Library cache pin instance enqueue (K=namespace)',
'NK','Library cache pin instance enqueue (L=namespace)',
'NM','Library cache pin instance enqueue (M=namespace)',
'NN','Library cache pin instance enqueue (N=namespace)',
'NO','Library cache pin instance enqueue (O=namespace)',
'NP','Library cache pin instance enqueue (P=namespace)',
'NQ','Library cache pin instance enqueue (Q=namespace)',
'NR','Library cache pin instance enqueue (R=namespace)',
'NS','Library cache pin instance enqueue (S=namespace)',
'NT','Library cache pin instance enqueue (T=namespace)',
'NU','Library cache pin instance enqueue (U=namespace)',
'NV','Library cache pin instance enqueue (V=namespace)',
'NW','Library cache pin instance enqueue (W=namespace)',
'NX','Library cache pin instance enqueue (X=namespace)',
'NY','Library cache pin instance enqueue (Y=namespace)',
'NZ','Library cache pin instance enqueue (Z=namespace)',
'QA','Row cache instance enqueue (A=cache)',
'QB','Row cache instance enqueue (B=cache)',
'QC','Row cache instance enqueue (C=cache)',
'QD','Row cache instance enqueue (D=cache)',
'QE','Row cache instance enqueue (E=cache)',
'QF','Row cache instance enqueue (F=cache)',
'QG','Row cache instance enqueue (G=cache)',
'QH','Row cache instance enqueue (H=cache)',
'QI','Row cache instance enqueue (I=cache)',
'QJ','Row cache instance enqueue (J=cache)',
'QL','Row cache instance enqueue (K=cache)',
'QK','Row cache instance enqueue (L=cache)',
'QM','Row cache instance enqueue (M=cache)',
'QN','Row cache instance enqueue (N=cache)',
'QO','Row cache instance enqueue (O=cache)',
'QP','Row cache instance enqueue (P=cache)',
'QQ','Row cache instance enqueue (Q=cache)',
'QR','Row cache instance enqueue (R=cache)',
'QS','Row cache instance enqueue (S=cache)',
'QT','Row cache instance enqueue (T=cache)',
'QU','Row cache instance enqueue (U=cache)',
'QV','Row cache instance enqueue (V=cache)',
'QW','Row cache instance enqueue (W=cache)',
'QX','Row cache instance enqueue (X=cache)',
'QY','Row cache instance enqueue (Y=cache)',
'QZ','Row cache instance enqueue (Z=cache)',
KSQSTTYP) "Enqueue Name",
KSQSTGET "Total Gets",
KSQSTWAT "Total waits"
from sys.x_$ksqst
where KSQSTWAT <> 0
order by KSQSTWAT
/
exit;

