set lines 200 feed off echo off veri off
PROMPT
COL BLOCK_SIZE          HEAD "Block|Size|KB"
COL INITIAL_EXTENT      HEAD "Initial|Ext|KB"
COL NEXT_EXTENT         HEAD "Next|Ext|KB"
COL MIN_EXTENTS         HEAD "Min|Ext"
COL MAX_EXTENTS         HEAD "Max|Ext"
COL PCT_INCREASE        HEAD "PCT|Inc"
COL EXTENT_MANAGEMENT   HEAD "Extent|Mgmt"
COL ALLOCATION_TYPE     HEAD "Alloc|Type"
COL SEGMENT_SPACE_MANAGEMENT    HEAD "Seg|Space|Mgmt"
COL BIGFILE             FOR A5  HEAD "Is|Big|File?"

SELECT TABLESPACE_NAME,
       BLOCK_SIZE/1024 BLOCK_SIZE,
       INITIAL_EXTENT/1024 INITIAL_EXTENT,
       NEXT_EXTENT/1024 NEXT_EXTENT,
       MIN_EXTENTS,
       MAX_EXTENTS,
       PCT_INCREASE,
       EXTENT_MANAGEMENT,
       ALLOCATION_TYPE,
       SEGMENT_SPACE_MANAGEMENT,
       BIGFILE
FROM   dba_tablespaces
/
PROMPT
exit
